services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - auth-db
    networks:
      - microservice

  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    networks:
      - microservice

networks:
  microservice:
    driver: bridge
