services:
    auth-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - ./keys:/var/www/html/keys
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: auth_db
            DB_USERNAME: root
            DB_PASSWORD: root
        command: >
            sh -c "
              composer install &&
              php artisan migrate --force &&
              php artisan test &&
              php artisan serve --host=0.0.0.0 --port=8000
            "

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: auth_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
    mysql_data:
networks:
    default:
        name: shared-network
        external: true
